# Floating Population of Women Between(15 - 44) by Neighborhood in Seoul
(Neighborhood is a smallest administrative division in South Korea)
### 1. The raw data is based on celluar data (https://www.data.go.kr/dataset/3053773/fileData.do) and has hourly data of floating population segmented on the basis of age range and gender by towns between Sep 1 ~ 30 2018. 
### 2. The data will be filtered to find the top 5 towns in women's floating population between 15 - 44 years old 
### 3. Top 5 towns are as below 
1. 11680640 강남구 역삼1동 
2. 11440660 마포구 서교동 
3. 11410585 서대문구 신촌동 
4. 11560540 영등포구 여의동 
5. 11110615 종로구 종로1.2.3.4가동

## Top 1 location in google map
![title](top1.png)
## Top 2 location in google map
![title](top2.png)

In [171]:
import pandas as pd

In [172]:
# Read data of Sep 2018
df = pd.read_csv('floating-population-201809.csv')

# fix wrong column assignment
df.columns = ['시간대구분', '행정동코드', '총생활인구수', '남자0세부터9세생활인구수', '남자10세부터14세생활인구수',
       '남자15세부터19세생활인구수', '남자20세부터24세생활인구수', '남자25세부터29세생활인구수',
       '남자30세부터34세생활인구수', '남자35세부터39세생활인구수', '남자40세부터44세생활인구수',
       '남자45세부터49세생활인구수', '남자50세부터54세생활인구수', '남자55세부터59세생활인구수',
       '남자60세부터64세생활인구수', '남자65세부터69세생활인구수', '남자70세이상생활인구수', '여자0세부터9세생활인구수',
       '여자10세부터14세생활인구수', '여자15세부터19세생활인구수', '여자20세부터24세생활인구수',
       '여자25세부터29세생활인구수', '여자30세부터34세생활인구수', '여자35세부터39세생활인구수',
       '여자40세부터44세생활인구수', '여자45세부터49세생활인구수', '여자50세부터54세생활인구수',
       '여자55세부터59세생활인구수', '여자60세부터64세생활인구수', '여자65세부터69세생활인구수',
       '여자70세이상생활인구수', 'dummy']


# Set index name 
df.index.name = '기준일'
df

# choose columns to show 
df_choose_fields = df[['시간대구분', '행정동코드', '총생활인구수', '여자15세부터19세생활인구수', '여자20세부터24세생활인구수', '여자25세부터29세생활인구수', '여자30세부터34세생활인구수', '여자35세부터39세생활인구수', '여자40세부터44세생활인구수']]
df_choose_fields

# export file because fixed df cause an 'slice...'error
df_choose_fields.to_csv('chosen-fields.csv',index=True)

In [153]:

# read chosen-fields file 
ndf = pd.read_csv('chosen-fields.csv')

# Add new field of Prospecct_Sum for women between 15 to 44
ndf['Prospecct_Sum'] = ndf['여자15세부터19세생활인구수'] + ndf['여자20세부터24세생활인구수'] + ndf['여자30세부터34세생활인구수'] + ndf['여자35세부터39세생활인구수'] + ndf['여자40세부터44세생활인구수']

ndf

,기준일,시간대구분,행정동코드,총생활인구수,여자15세부터19세생활인구수,여자20세부터24세생활인구수,여자25세부터29세생활인구수,여자30세부터34세생활인구수,여자35세부터39세생활인구수,여자40세부터44세생활인구수,Prospecct_Sum
0,20180901,0,11110515,13976.7333,394.4693,396.7610,429.8679,457.9480,587.3650,737.2831,2573.8264
1,20180901,0,11110530,17531.9424,383.1192,474.8597,725.2958,677.9527,762.3630,753.9456,3052.2402
2,20180901,0,11110540,4562.9781,104.5722,109.5849,104.1068,116.3493,186.6914,160.8649,678.0627
3,20180901,0,11110550,12737.1668,436.7896,436.9062,341.5433,384.1300,495.0951,503.7212,2256.6421
4,20180901,0,11110560,23056.2094,648.3811,711.6346,535.6463,668.7291,815.2118,813.9095,3657.8661
5,20180901,0,11110570,8589.2779,236.2758,227.5294,251.5300,248.5042,363.5806,339.8517,1415.7417
6,20180901,0,11110580,6916.9581,219.1399,230.6787,248.4588,221.5914,283.6841,284.1096,1239.2037
7,20180901,0,11110600,4793.9797,130.3794,120.5526,138.0438,173.5298,192.8849,203.4279,820.7746
8,20180901,0,11110615,33210.9008,347.5349,1642.2565,1983.6006,1309.7535,1043.8167,840.5766,5183.9382
9,20180901,0,11110630,11370.6734,197.7398,487.2472,450.0874,321.8201,334.0050,336.5859,1677.3980
10,20180901,0,11110640,16588.7299,334.1997,999.6827,1056.1137,786.3252,710.1379,508.6340,3338.9795
11,20180901,0,11110650,32959.8161,1418.6266,3351.8346,1732.5904,1114.2330,1033.9127,967.4327,7886.0396
12,20180901,0,11110670,12716.1133,164.8910,434.6051,531.6082,458.7996,584.5256,528.9860,2171.8073
13,20180901,0,11110680,10719.8622,314.7563,332.9542,404.8319,356.1688,354.9129,264.8270,1623.6192
14,20180901,0,11110690,5515.2790,155.7720,174.7811,182.0131,209.1130,271.6642,222.3154,1033.6457
15,20180901,0,11110700,7622.3570,158.0647,283.0046,286.7138,263.6186,295.5752,266.8567,1267.1198
16,20180901,0,11110710,13676.9253,224.8171,724.1642,793.9251,643.1077,604.7222,430.4723,2627.2835
17,20180901,0,11140520,9612.8834,132.9346,284.3006,476.4635,396.6537,433.2099,390.5055,1637.6043
18,20180901,0,11140540,10632.3042,98.7736,305.4158,396.9038,505.0626,449.4016,415.6832,1774.3368
19,20180901,0,11140550,12263.6255,187.2040,664.8087,803.9329,540.7144,518.8710,379.0808,2290.6789
20,20180901,0,11140570,8910.8608,269.4140,619.6976,404.6880,334.1477,265.2579,231.5041,1720.0213
21,20180901,0,11140580,8298.9417,212.4193,677.7567,531.4669,370.9869,339.9528,214.1999,1815.3156
22,20180901,0,11140590,19746.2069,300.3890,1253.1402,1401.0793,1203.6424,968.8081,679.2932,4405.2729
23,20180901,0,11140605,7880.7280,59.2457,301.5578,350.1447,294.8371,241.9656,189.2195,1086.8257
24,20180901,0,11140615,33907.4590,296.3352,1472.3045,1955.3805,1984.7032,2435.8842,1682.1860,7871.4131
25,20180901,0,11140625,17164.6730,392.0843,646.8142,823.4016,723.5991,649.0313,587.3105,2998.8394
26,20180901,0,11140635,18442.1741,314.1166,481.7191,630.4476,805.8281,869.4691,810.7562,3281.8891
27,20180901,0,11140645,13856.6938,287.6334,417.6202,530.3128,690.3131,623.1522,511.5392,2530.2581
28,20180901,0,11140650,12354.7280,194.8102,440.7422,516.6971,553.4688,593.5300,431.3559,2213.9071
29,20180901,0,11140665,10031.4077,236.6382,320.7296,390.9040,399.9820,436.8228,355.5005,1749.6731
...,...,...,...,...,...,...,...,...,...,...,...
264546,20180930,23,11710610,36423.0385,687.4647,1089.5570,1920.9371,2145.0738,2023.6917,1480.6782,7426.4654
264547,20180930,23,11470610,4981.1480,149.5048,141.7407,139.4035,133.8961,206.9166,211.3888,843.4470
264548,20180930,23,11740570,33833.0769,753.7152,908.1408,1218.3512,1285.6410,1455.5925,1264.6608,5667.7503
264549,20180930,23,11350624,22766.3256,672.4603,764.8872,571.2528,565.5095,677.0907,987.3579,3667.3056
264550,20180930,23,11500620,35419.5843,641.3812,1183.4578,1329.2234,1496.1520,1651.9253,1327.6414,6300.5577
264551,20180930,23,11140520,7390.8150,419.2551,226.0343,300.9049,288.7825,260.6675,263.6044,1458.3438
264552,20180930,23,11110540,5013.6806,114.2022,115.8233,125.5277,148.4179,193.6536,197.4336,769.5306
264553,20180930,23,11260620,35132.1147,786.9901,1187.0427,1228.0042,1383.1695,1499.5266,1310.0130,6166.7419
264554,20180930,23,11620605,31939.0209,606.1059,1130.0589,1557.7685,1438.0655,1486.6346,1269.7568,5930.6217
264555,20180930,23,11170640,9307.0400,144.1825,242.6450,308.6072,408.6648,346.1785,389.6113,1531.2821
264556,20180930,23,11380580,25989.6735,1237.8120,738.4668,876.5855,965.2817,1085.2084,990.8048,5017.5737
264557,20180930,23,11140680,7045.7088,123.5190,201.0149,263.0739,391.2565,321.4785,289.8325,1327.1014
264558,20180930,23,11740685,60408.3887,1362.8399,1892.8906,2306.3193,2261.2603,2544.1089,2287.0386,10348.1383
264559,20180930,23,11740520,18681.6666,567.4836,450.9675,490.2765,606.4230,666.3122,673.0212,2964.2075
264560,20180930,23,11350640,27027.3619,866.4987,1504.0600,1048.1105,851.0015,758.2467,762.7982,4742.6051
264561,20180930,23,11500570,22562.2947,490.0857,539.1600,784.3532,917.4241,1109.1874,879.3522,3935.2094
264562,20180930,23,11680690,21163.4972,635.9847,551.6755,741.9757,906.3046,816.7026,903.2271,3813.8945
264563,20180930,23,11620745,27669.1779,717.7306,1099.9427,992.1346,848.7057,903.4271,862.6333,4432.4394
264564,20180930,23,11650621,26528.9604,810.6722,834.4249,1000.5287,1114.2240,1087.3621,1178.7126,5025.3958
264565,20180930,23,11680545,34465.2070,888.7009,984.1803,1082.3227,1236.8720,1582.6124,1520.5539,6212.9195
264566,20180930,23,11740530,28836.3140,871.1276,836.0537,844.5101,943.1755,1090.2832,1258.9085,4999.5485
264567,20180930,23,11680750,20864.1579,457.7611,422.0355,760.2512,859.3513,889.0956,661.8006,3290.0441
264568,20180930,23,11200660,16927.3915,303.2157,650.9909,815.1506,911.5540,742.1138,609.4732,3217.3476
264569,20180930,23,11410555,33441.0577,623.3162,1659.0035,1526.7631,1753.2159,1619.3267,1335.6901,6990.5524
264570,20180930,23,11350580,30288.6124,648.4907,906.1171,865.1750,1132.9947,1402.9722,1295.1561,5385.7308
264571,20180930,23,11170660,13510.7346,155.6165,455.0891,787.0117,978.4357,792.7746,565.8716,2947.7875
264572,20180930,23,11680656,28773.7130,991.7465,839.6735,781.0485,857.1787,1204.7711,1431.9325,5325.3023
264573,20180930,23,11380551,26088.1358,707.4112,993.8041,1080.0631,1011.2640,964.0874,804.0073,4480.5740
264574,20180930,23,11710580,32757.4969,733.9040,1112.5014,1915.6721,1919.2260,1702.6250,1163.5862,6631.8426
264575,20180930,23,11710561,17713.8305,521.7844,591.7237,588.7417,548.5040,720.2777,704.8299,3087.1197

In [154]:
# select only 기준일', '시간대구분', '행정동코드', '총생활인구수', '행정동코드1', 'sum'
adf = ndf[['기준일', '시간대구분', '총생활인구수', '행정동코드', 'Prospecct_Sum']]
adf

             기준일  시간대구분      총생활인구수     행정동코드  Prospecct_Sum
0       20180901      0  13976.7333  11110515      2573.8264
1       20180901      0  17531.9424  11110530      3052.2402
2       20180901      0   4562.9781  11110540       678.0627
3       20180901      0  12737.1668  11110550      2256.6421
4       20180901      0  23056.2094  11110560      3657.8661
5       20180901      0   8589.2779  11110570      1415.7417
6       20180901      0   6916.9581  11110580      1239.2037
7       20180901      0   4793.9797  11110600       820.7746
8       20180901      0  33210.9008  11110615      5183.9382
9       20180901      0  11370.6734  11110630      1677.3980
10      20180901      0  16588.7299  11110640      3338.9795
11      20180901      0  32959.8161  11110650      7886.0396
12      20180901      0  12716.1133  11110670      2171.8073
13      20180901      0  10719.8622  11110680      1623.6192
14      20180901      0   5515.2790  11110690      1033.6457
15      20180901      0   7622.3570  11110700      1267.1198
16      20180901      0  13676.9253  11110710      2627.2835
17      20180901      0   9612.8834  11140520      1637.6043
18      20180901      0  10632.3042  11140540      1774.3368
19      20180901      0  12263.6255  11140550      2290.6789
20      20180901      0   8910.8608  11140570      1720.0213
21      20180901      0   8298.9417  11140580      1815.3156
22      20180901      0  19746.2069  11140590      4405.2729
23      20180901      0   7880.7280  11140605      1086.8257
24      20180901      0  33907.4590  11140615      7871.4131
25      20180901      0  17164.6730  11140625      2998.8394
26      20180901      0  18442.1741  11140635      3281.8891
27      20180901      0  13856.6938  11140645      2530.2581
28      20180901      0  12354.7280  11140650      2213.9071
29      20180901      0  10031.4077  11140665      1749.6731
...          ...    ...         ...       ...            ...
264546  20180930     23  36423.0385  11710610      7426.4654
264547  20180930     23   4981.1480  11470610       843.4470
264548  20180930     23  33833.0769  11740570      5667.7503
264549  20180930     23  22766.3256  11350624      3667.3056
264550  20180930     23  35419.5843  11500620      6300.5577
264551  20180930     23   7390.8150  11140520      1458.3438
264552  20180930     23   5013.6806  11110540       769.5306
264553  20180930     23  35132.1147  11260620      6166.7419
264554  20180930     23  31939.0209  11620605      5930.6217
264555  20180930     23   9307.0400  11170640      1531.2821
264556  20180930     23  25989.6735  11380580      5017.5737
264557  20180930     23   7045.7088  11140680      1327.1014
264558  20180930     23  60408.3887  11740685     10348.1383
264559  20180930     23  18681.6666  11740520      2964.2075
264560  20180930     23  27027.3619  11350640      4742.6051
264561  20180930     23  22562.2947  11500570      3935.2094
264562  20180930     23  21163.4972  11680690      3813.8945
264563  20180930     23  27669.1779  11620745      4432.4394
264564  20180930     23  26528.9604  11650621      5025.3958
264565  20180930     23  34465.2070  11680545      6212.9195
264566  20180930     23  28836.3140  11740530      4999.5485
264567  20180930     23  20864.1579  11680750      3290.0441
264568  20180930     23  16927.3915  11200660      3217.3476
264569  20180930     23  33441.0577  11410555      6990.5524
264570  20180930     23  30288.6124  11350580      5385.7308
264571  20180930     23  13510.7346  11170660      2947.7875
264572  20180930     23  28773.7130  11680656      5325.3023
264573  20180930     23  26088.1358  11380551      4480.5740
264574  20180930     23  32757.4969  11710580      6631.8426
264575  20180930     23  17713.8305  11710561      3087.1197

[264576 rows x 5 columns]

In [168]:
# filters data during 0 am - 6am and after 10 pm
tdf = adf[(adf['시간대구분']>=7) & (adf['시간대구분'] < 23)]
tdf

             기준일  시간대구분      총생활인구수     행정동코드  Prospecct_Sum
2968    20180901      7  14839.2369  11110515      2655.5997
2969    20180901      7  18830.6956  11110530      3004.2382
2970    20180901      7   4693.3124  11110540       645.7205
2971    20180901      7  13279.6757  11110550      2438.3727
2972    20180901      7  24148.9346  11110560      3772.3803
2973    20180901      7   7734.6946  11110570      1312.3482
2974    20180901      7   7079.7736  11110580      1210.4445
2975    20180901      7   5208.9199  11110600       869.6886
2976    20180901      7  32190.7355  11110615      4610.9085
2977    20180901      7  13704.2260  11110630      1604.0971
2978    20180901      7  18583.1740  11110640      3695.8312
2979    20180901      7  29848.4322  11110650      7120.0317
2980    20180901      7  11927.2718  11110670      1889.6115
2981    20180901      7   9873.9841  11110680      1576.9902
2982    20180901      7   5009.3978  11110690       902.1135
2983    20180901      7   8019.5289  11110700      1306.5980
2984    20180901      7  14675.3600  11110710      2681.7669
2985    20180901      7  11778.6386  11140520      1879.2955
2986    20180901      7  15663.0871  11140540      2384.8094
2987    20180901      7  13994.5486  11140550      2360.9265
2988    20180901      7   9799.2498  11140570      1760.5773
2989    20180901      7   9274.8049  11140580      1959.2435
2990    20180901      7  15956.0025  11140590      2740.9311
2991    20180901      7  10225.9224  11140605       978.4099
2992    20180901      7  23590.1671  11140615      4429.5168
2993    20180901      7  17099.5900  11140625      3202.3657
2994    20180901      7  17569.9048  11140635      3111.1743
2995    20180901      7  14402.8283  11140645      2740.7471
2996    20180901      7  12218.3434  11140650      2268.8453
2997    20180901      7   8967.0952  11140665      1580.8833
...          ...    ...         ...       ...            ...
264122  20180930     22  14340.1273  11110550      2703.7840
264123  20180930     22  15425.3399  11320681      2422.0570
264124  20180930     22  36382.1267  11650531      7756.6466
264125  20180930     22  19609.2096  11590520      3384.9742
264126  20180930     22  42021.7765  11410720      7133.7144
264127  20180930     22  18228.9021  11350700      3589.8753
264128  20180930     22  28709.3158  11290575      7920.4399
264129  20180930     22  10962.1312  11140540      2032.4714
264130  20180930     22  39233.9076  11710642      7987.3432
264131  20180930     22  18977.1922  11260690      3117.3134
264132  20180930     22  33778.8365  11620565      6127.6930
264133  20180930     22  26128.2543  11740640      4788.0883
264134  20180930     22  22831.0211  11620775      3664.1781
264135  20180930     22  42039.9731  11440730      8447.3248
264136  20180930     22  25794.6372  11620745      4175.8353
264137  20180930     22  12990.9878  11380650      2219.9899
264138  20180930     22  39126.9981  11710647      7673.6672
264139  20180930     22  35548.2027  11530510      7351.9284
264140  20180930     22  16227.4963  11470630      2750.8539
264141  20180930     22  47680.1235  11470510      8981.5492
264142  20180930     22  19705.5069  11590640      3499.8611
264143  20180930     22  28315.9345  11170685      5845.7636
264144  20180930     22  22671.4835  11710566      3858.1609
264145  20180930     22  29651.6815  11440655      6932.5888
264146  20180930     22  17006.5974  11590650      3253.7131
264147  20180930     22  36474.4807  11500510      7396.3539
264148  20180930     22  14501.3847  11470590      2359.0472
264149  20180930     22  18227.2909  11110530      3382.4322
264150  20180930     22  26700.6102  11350670      4238.2699
264151  20180930     22  18637.1756  11560650      2819.0594

[176384 rows x 5 columns]

In [156]:
# group the same towns and calculate the mean number of Prospect_Sum of the towns 
# gdf = tdf.groupby('행정동코드')
tdf['Prospecct_Sum-Mean'] = tdf.groupby('행정동코드')['Prospecct_Sum'].transform('mean')

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [157]:
# group by the towns again to get the described data 
gdf = tdf.groupby('행정동코드')
kdf = gdf.describe()

In [161]:
# Top 5 towns among the data 

sdf = kdf['Prospecct_Sum-Mean']
fdf = sdf.sort_values(by=['mean'], ascending=[False]).head(5)
fdf

,count,mean,std,min,25%,50%,75%,max
행정동코드,,,,,,,,
11680640,338.0,29382.748306,3.643372e-12,29382.748306,29382.748306,29382.748306,29382.748306,29382.748306
11440660,338.0,26473.315688,3.643372e-12,26473.315688,26473.315688,26473.315688,26473.315688,26473.315688
11410585,338.0,24525.470374,3.643372e-12,24525.470374,24525.470374,24525.470374,24525.470374,24525.470374
11560540,338.0,23028.592308,3.643372e-12,23028.592308,23028.592308,23028.592308,23028.592308,23028.592308
11110615,338.0,17392.019520,3.643372e-12,17392.019520,17392.019520,17392.019520,17392.019520,17392.019520

11680640 강남구 역삼1동 
11440660 마포구 서교동 
11410585 서대문구 신촌동 
11560540 영등포구 여의동 
11110615 종로구 종로1.2.3.4가동